### ISSUE TITLE
Syncronize with transifex

### ISSUE THREAD

**Issue by cvvergara** [MobilityDB/MobilityDB#106]
Automatically syncronize with transifex

To be able to continue, as I do not know docbook, 
I need to know how the pot files in transifex are currently generated.

This I already tried xml2po is not available any more on focal fossa because the package gnome-doc-utils is written with python2 and focal uses python 3. So its no longer compatible.

**Comment by estebanzimanyi** [comment]
Interesting that (according to my understanding) MSYS2 includes xml2po for python3
https://packages.msys2.org/package/gnome-doc-utils
Would that leads us to a possible solution ?

**Comment by cvvergara** [comment]
bionic has it, but I am not going to install bionic on my focal computer
https://packages.ubuntu.com/search?keywords=gnome-doc-utils
So what can we do: I don't know, I didn't decide on docbook
will ask around

**Comment by cvvergara** [comment]
@estebanzimanyi 
To do the syncronization as I am not owner of mobilitydb I can not do this steps. 
https://docs.transifex.com/transifex-github-integrations/github-tx-ui
Please do them for me.

**Comment by estebanzimanyi** [comment]
This small bash file generates all the .pot files from the xml files. 
```
#!/bin/bash

for f in `find . -name '*.xml'`; do
  echo "Processing $f file...";
  xml2pot ${f} > "$f.pot";
done

exit 0
```
When run from the MobilityDB/doc directory it also generates the .pot files in the MobilityDB/doc/es directory

**Comment by cvvergara** [comment]
Ok, got that one: xml2pot

**Comment by cvvergara** [comment]
Did you follow the steps here 
https://docs.transifex.com/transifex-github-integrations/github-tx-ui
to have transifex syncronized with the repository?
I still dont see the "integrations" tab on the transifex settings

**Comment by estebanzimanyi** [comment]
Normally yes. Please look at the screen captures I sent you on gitter.

**Comment by estebanzimanyi** [comment]
BTW I am currently synchronizing by hand the English and Spanish
documentation and ensuring a proper XML encoding so that xml2pot extracts
correct strings. When this is done I will make a PR with the new version of
the documentation, including the pot and po files so we can start the
integration with Transifex.

**Comment by cvvergara** [comment]
Need the exact steps, to be able to automate the process

**Comment by estebanzimanyi** [comment]
For the moment I am producing by hand what would be output of Transifex,
i.e., all the po files such as

#. Tag: para
#: introduction.xml:23
#, no-c-format
msgid ""
"The current members in alphabetical order and their main responsibilities "
"are given next:"
msgstr ""
"A continuación se detallan los miembros actuales en orden alfabético y sus
"
"principales responsabilidades:"

#. Tag: para
#: introduction.xml:26
#, no-c-format
msgid ""
"Mohamed Bakli: <ulink url=\"https://github.com/MobilityDB/MobilityDB-docker
"
"\">MobilityDB-docker</ulink>, cloud and distributed versions, integration "
"with <ulink url=\"https://www.citusdata.com/\">Citus</ulink>"
msgstr ""
"Mohamed Bakli: <ulink url=\"https://github.com/MobilityDB/MobilityDB-docker
"
"\">MobilityDB-docker</ulink>, versiones distribuidas y en la nube, "
"integración con <ulink url=\"https://www.citusdata.com/\">Citus</ulink>"

Then we should investigate what will be the process for updating the manual
in a sustainable way so that we do not need to repeat all the manual work I
am doing now.

**Comment by cvvergara** [comment]
Think that instead of Spanish its Japanese, which I would think you wouldn't translate.
How do you update transifex English documentation for the Japanese person to translate?
- How you create the pot files?
- How you upload the pot files to transifex?
- How do you download a japanese translation from transifex?

**Comment by estebanzimanyi** [comment]
Thanks for these steps !!! This is exactly what I going to investigate now that I have finished to synchronize the xml, po and pot files.

**Comment by cvvergara** [comment]
I didnt give you steps, I want to know how you do those steps.

**Comment by estebanzimanyi** [comment]
Here is the current status of my investigations.

To validate the source (English) manual
```
xmllint --xinclude --postvalid mobilitydb-manual.xml > /dev/null
```
To generate the pot file (in the directory MobilityDB/doc)
```
xml2pot file > file.pot
```
To generate the translated xml files from the po files with the translations (in the directory MobilityDB/doc/es)
```
po2xml ../introduction.xml introduction.xml.po > introduction_new.xml
```
The result is correct and can be used to generated, e.g., the pdf with the command `dblatex`

The problem is that the output is not nicely formatted
```
<chapter id ="introduction">
	<title
>Introducción </title>
	<para
>MobilityDB es una extensión de <ulink url="http://postgresql.org"
> PostgreSQL</ulink
> y <ulink url="http://postgis.net"
> PostGIS</ulink
> que proporciona <emphasis
>tipos temporales</emphasis
```
Therefore, an xml pretty-printer is needed. `tidy` is a solution
```
tidy -quiet --show-warnings false -w -xml -indent introduction_new1.xml > introduction_new1_tidy.xml
```
and produces the following result
```
<chapter id="introduction">
  <title>Introducción</title>
  <para>MobilityDB es una extensión de 
  <ulink url="http://postgresql.org">PostgreSQL</ulink>y 
  <ulink url="http://postgis.net">PostGIS</ulink>que proporciona 
  <emphasis>tipos temporales</emphasis>. Dichos tipos de datos representan la evolución en el tiempo de los valores de algún tipo de elemento, 
[...]
```

To avoid using another program I asked a question on stackoverflow
https://stackoverflow.com/questions/68603584/xmllint-format-entities-not-defined

Now it remains to integrate all this with Transifex. Since you surely know Transifex better than me, any suggestion in this respect is more than welcome.

**Comment by cvvergara** [comment]
![image](https://user-images.githubusercontent.com/5035290/127790616-c630ed9b-d130-4207-8fd5-d0095fce4574.png)

I think you will need to learn as I can't do it.

**Comment by estebanzimanyi** [comment]
I have made the integration with the following yaml configuration
```
filters:
  - filter_type: dir
    # all supported i18n types: https://docs.transifex.com/formats
    file_format: PO
    source_file_extension: pot
    source_language: en
    source_file_dir: doc/source.pot
    # path expression to translation files, must contain <lang> placeholder
    translation_files_expression: 'doc/<lang>/translation.po'
```
Nevertheless, the message received is "Aucun article n’a été trouvé pour la synchronisation."

**Comment by cvvergara** [comment]
I can not help: I cant access that to do try and error
This is the setup in pgRouting:
```
filters:
  - filter_type: dir
    file_format: PO
    source_file_extension: po
    source_language: en
    source_file_dir: locale/en/LC_MESSAGES
    translation_files_expression: locale/<lang>/LC_MESSAGES
```
We keep things separate, documentation is always English, and files for translation are pot and po. we never save the rst of the translated file as its generated automatically and pushed into the gh-pages branch. Our manual task is just click a button basically to have all the process done automatically (until we find a way to not trigger the documentation generation on forks)

Where, the original rst files are in the directory doc
The related files with translation with transifex (po, pot) are in directory locale.
```
doc
├── allpairs
├── alpha_shape
├── astar
├── etc


locale
├── en
├── es
├── ja
└── pot
```
Also now that you are learning, why don't you try the xml format that transifex allows as input instead of pot & po,
https://docs.transifex.com/formats/java-xml-properties

For the po & pot files in the github actions either using macos, ubuntu or windows, converting the xml2po is needed, and knowing that ubuntu does not have the gnome-doc-utils so ubuntu is out of the question. So I recommend to test your processes with translations on windows or mac and see if one works. (github actions support mac and windows)

**Comment by estebanzimanyi** [comment]
I changed the yaml file as follows and it worked !!!
```
filters:
  - filter_type: dir
    # all supported i18n types: https://docs.transifex.com/formats
    file_format: PO
    source_file_extension: pot
    source_language: en
    source_file_dir: doc/
    # path expression to translation files, must contain <lang> placeholder
    translation_files_expression: doc/<lang>/
```
Finding the workflow from docbook -> pot -> po -> docbook with all the required intermediate steps (pretty-printer, sed, ...) that works and is able to generate the documentation files from the output (e.g., using dblatex) took me quite a long time. I cannot foresee to find a similar workflow for java-xml-properties.
